---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - fluxcd.rawkode.dev
  resources:
  - sourcetransformers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluxcd.rawkode.dev
  resources:
  - sourcetransformers/finalizers
  verbs:
  - update
- apiGroups:
  - fluxcd.rawkode.dev
  resources:
  - sourcetransformers/status
  verbs:
  - get
  - patch
  - update
